# Numpy

¿Cuál es el hype de Numpy?

Hemos mencionado que es una paquetería utilizada ampliamente en la industria, pero ¿qué la hace tan especial?

Comencemos explorando el objeto principal de Numpy: el `ndarray`.

## `ndarray`
**Un ndarray (N-dimensional array) es la estructura de datos principal de NumPy que permite almacenar y manipular arrays (arreglos) multidimensionales de forma eficiente. Proporciona operaciones rápidas y flexibles para realizar cálculos numéricos y transformaciones en grandes conjuntos de datos.**

En un ndarray podemos almacenar elementos de un mismo tipo de dato. Aquí uno podría preguntarse

**¿cuál es la ventaja o el beneficio de usar un ndarray de Numpy sobre una lista ordinaria de Python?**

Numpy tiene ventajas significativas sobre listas ordinarias, descubrámoslas con ejemplos prácticos

---

## Crear un arreglo de Numpy
Hay más de una forma (como es costumbre en Python) para crear un array. La más común es pasarle una lista a la función `np.array`

In [1]:
#Importamos numpy como np (SIEMPRE)
import numpy as np

In [2]:
lista = [0,1,2,3,4]
array_1d = np.array(lista)

#Checamos el tipo de dato de array_id
type(array_1d)

numpy.ndarray

In [3]:
type(1.2)

float

In [4]:
#contenido del array
array_1d

array([0, 1, 2, 3, 4])

## Diferencia entre ndarray y lista

La diferencia principal entre un `array` y una `list` es que los `arrays` están diseñados para procesar operaciones vectorizadas, mientras que una lista no tiene estas capacidades.

Sea $\vec{x}$ un vector tal que $\vec{x} = (0 , 1, 2, 3, 4)$

$$\vec{x} + a = (0 + a, 1 + a, 2 + a, 3 + a, 4 + a)$$

Entonces, si $a = 2$
$$ \vec{x} + 2 = (0 +2, 1 + 2, 2 + 2, 3 + 2, 4 + 2) $$
$$ \vec{x} + 2 = (2, 3, 4, 5, 6) $$

Esto significa que si aplicamos una función a un `array` entonces la función se va a aplicar a **cada elemento del array**

Veamos un ejemplo:

Si quisieramos sumar 2 a cada elemento de la `lista`, intuitivamente podríamos intentar:

In [5]:
lista

[0, 1, 2, 3, 4]

In [6]:
lista + 2

TypeError: can only concatenate list (not "int") to list

Como podemos ver, no es posible hacer esto con listas. Probemos ahora con `array_1d`

In [8]:
array_1d + 2

array([2, 3, 4, 5, 6])

---

### Otro ejemplo: Multiplicación de matrices

Veamos una multiplicación de matrices con Numpy.

$A=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}$ , $B=\begin{bmatrix}
7 & 8 \\
9 & 10 \\
11 & 12
\end{bmatrix}$

Recordemos de la materia de Álgebra Lineal que:
Sean A y B, 2 matrices

$\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}
\end{bmatrix}
\begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22} \\
b_{31} & b_{32}
\end{bmatrix}
=
\begin{bmatrix}
a_{11}b_{11} + a_{12}b_{21} + a_{13}b_{31} & a_{11}b_{12} + a_{12}b_{22} + a_{13}b_{32} \\
a_{21}b_{11} + a_{22}b_{21} + a_{23}b_{31} & a_{21}b_{12} + a_{22}b_{22} + a_{23}b_{32}
\end{bmatrix}$

---

Antes de apreciar la **BELLEZA** de Numpy, hagamos una implementación de multiplicación de matrices sin utilizar numpy:

In [9]:
def multiplicar_matrices(A, B):
    # obtener dimensiones
    filas_A = len(A)
    cols_A = len(A[0])
    filas_B = len(B)
    cols_B = len(B[0])

    # checar si se pueden multiplicar A y B
    if cols_A != filas_B:
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")

    # Inicializar una matriz vacía con ceros
    matriz_resultado = []
    for _ in range(filas_A):
        fila = []
        for _ in range(cols_B):
            fila.append(0)
        matriz_resultado.append(fila)

    # realizar multiplicación
    for i in range(filas_A):
        for j in range(cols_B):
            for k in range(cols_A):
                matriz_resultado[i][j] += A[i][k] * B[k][j]

    return matriz_resultado

# Ejemplo
A = [
    [1, 2, 3],
    [4, 5, 6]
]
B = [
    [7, 8],
    [9, 10],
    [11, 12]
]
C = multiplicar_matrices(A, B)
print(C)

[[58, 64], [139, 154]]


**¿Nada mal no?**

Y de hecho se ejecutó bastante rápido… Pongámosle más estrés a Python con multiplicaciones de matrices más grandes, y contemos cuánto tarda en multiplicar cada una de ellas:

### Función para crear una matriz de NxN con números aleatorios

In [10]:
import random

def generar_matriz_aleatoria(N):
    matriz = []
    for i in range(N):
        fila = []
        for j in range(N):
            fila.append(random.randint(1, 9))
        matriz.append(fila)
    return matriz


N = 5
matriz_aleatoria = generar_matriz_aleatoria(N)
for fila in matriz_aleatoria:
    print(fila)

[4, 7, 3, 6, 6]
[4, 7, 4, 6, 5]
[8, 9, 7, 6, 1]
[2, 8, 7, 9, 3]
[5, 7, 4, 1, 6]


### Función para imprimir una matriz en formato amigable

In [11]:
def imprimir_matriz(matriz):
    for fila in matriz:
        fila_formateada = ' '.join(f'{elemento:2}' for elemento in fila)
        print(fila_formateada)

### Creación e impresión de las matrices

In [12]:
print("Matríz de 5x5:")
m_5 = generar_matriz_aleatoria(5)
imprimir_matriz(m_5)
print("====================")
print("Matríz de 10x10:")
m_10 = generar_matriz_aleatoria(10)
imprimir_matriz(m_10)
print("====================")
print("Matríz de 20x20:")
m_20 = generar_matriz_aleatoria(20)
imprimir_matriz(m_20)
print("====================")
m_100 = generar_matriz_aleatoria(100)

Matríz de 5x5:
 9  9  8  9  2
 2  2  3  7  3
 1  7  5  5  2
 9  2  6  3  4
 6  9  4  2  3
Matríz de 10x10:
 5  6  4  4  2  8  1  4  7  1
 8  5  4  9  4  8  5  1  3  1
 7  6  5  1  4  7  3  3  2  2
 3  9  2  6  1  3  2  8  9  9
 1  7  8  8  9  4  4  1  1  9
 9  5  1  4  8  2  5  7  9  9
 4  6  7  9  4  8  8  9  5  4
 4  5  3  8  1  9  6  1  1  4
 3  1  1  6  5  5  3  8  1  8
 1  7  9  3  9  3  7  4  4  7
Matríz de 20x20:
 3  9  2  8  5  1  6  5  4  1  3  1  7  9  8  3  1  7  6  8
 5  8  4  3  1  8  3  4  3  4  7  7  5  6  9  4  3  9  6  7
 8  5  2  3  8  9  7  6  4  6  5  2  6  6  9  8  3  9  8  3
 1  2  3  2  4  3  7  4  1  3  2  3  8  6  4  8  8  6  6  3
 5  2  3  2  6  9  5  5  1  8  9  6  8  3  7  5  4  5  4  5
 7  3  1  2  2  1  7  7  7  8  7  3  7  6  8  5  1  1  8  4
 8  9  2  3  5  3  2  8  2  2  8  2  3  4  3  6  8  5  9  3
 3  9  7  3  7  9  5  4  5  6  9  4  5  8  6  2  2  3  4  5
 2  4  2  3  5  9  7  5  1  9  3  4  1  9  2  5  8  9  4  9
 9  2  2  7  4  4  1  2  8  4  3  4 

---
Ahora midamos el tiempo que tardamos en multiplicar cada una de las matrices por sí misma. Utilizaremos código como éste
```python
start = time.time()
# ejecutar código
end = time.time()
tiempo = round(end - start, 5)
print(f"La ejecución tardó {tiempo} seg.")
```

In [13]:
import time

**Comencemos con la matrices de 5x5**

In [16]:
start = time.time()
multiplicar_matrices(m_5, m_5)
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 5x5 tardó {tiempo} seg.")

Multiplicar dos matrices de 5x5 tardó 9.703636169433594e-05 seg.


**Nada mal… Veamos ahora 10x10**

In [15]:
start = time.time()
multiplicar_matrices(m_10, m_10)
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 10x10 tardó {tiempo} seg.")

Multiplicar dos matrices de 10x10 tardó 0.0002570152282714844 seg.


**Parece que va bastante rápido... Intentemos ahora con una matriz de 1000x1000**

In [17]:
m_1000 = generar_matriz_aleatoria(1000)
start = time.time()
multiplicar_matrices(m_1000, m_1000)
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 1000x1000 tardó {tiempo} seg.")

KeyboardInterrupt: 

# Tardamos más de un minuto completo en multiplicar dos matrices de 1000x1000

---

## Implementación con Numpy

Veamos qué tanto mejora el rendimiento de multiplicación de matrices cuando implementamos numpy.

Primero, creemos una función para generar matrices:

In [18]:
def generar_matriz_aleatoria_numpy(N):
    return np.random.randint(1, 10, size=(N, N))

**No te preocupes por la sintaxis de Numpy. La revisaremos más adelante 😎**

In [19]:
m_1000 = generar_matriz_aleatoria_numpy(1000)

**Para multiplicar matrices en numpy, podemos utilizar la función `np.dot`, o bien, el operador `@`**

In [20]:
start = time.time()
np.dot(m_1000, m_1000)
# o bien, m_1000 @ m_1000
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 1000x1000 con Numpy tardó {tiempo} seg.")

Multiplicar dos matrices de 1000x1000 con Numpy tardó 1.8847250938415527 seg.


---

## Arreglos de 2 dimensiones
Un arreglo de dos dimensiones es lo mismo que una matriz de $m \times n$. Una matriz es la forma más adecauda de representar datos tabulares, Numpy hace su manejo sumamente fácil. Comencemos por crear una matriz de $3 \times 3$

Queremos hacer la siguiente matriz:
$$ \begin{bmatrix}
0 & 1 & 2 \\
3 & 4 & 5 \\
6 & 7 & 8
\end{bmatrix} $$

In [21]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Podemos especificar el tipo de dato cuando creamos nuestro `ndarray`, por lo general Numpy infiere el tipo de dato

In [22]:
arr2d_f = np.array(list2, dtype='float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [23]:
#convertir a enteros nuevamente
arr2d_f.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
# convertir a enteros y luego a strings
arr2d_f.astype('int').astype('str')

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U21')

Una diferencia importante entre listas y np.arrays es que una lista puede almacenar objetos de diferentes tipos de datos, mientras que un np.array debe ser consistente en el tipo de dato que almacena. Esto se debe al deseo que tenemos por realizar operaciones vectorizadas

In [25]:
# crear un arreglo de valroes lógicos o bools
arr2d_b = np.array([1, 0, 10, 11, 12, -1, 0], dtype='bool')
arr2d_b

array([ True, False,  True,  True,  True,  True, False])

Sí existe una forma de mantener la ambigüedad en el tipo de dato de nuestro array. Esto lo podemos logar si especificamos que el tipo de dato es `object`

In [26]:
arr1d_obj = np.array([1, 'a'], dtype='object')
arr1d_obj

array([1, 'a'], dtype=object)

Por último: podemos convertir un `ndarray` a una lista en cualquier momento utilziando el método `tolist()`

In [27]:
lista = arr1d_obj.tolist()
lista

[1, 'a']

O bien `list(numpy.ndarray)`

In [28]:
list(arr1d_obj)

[1, 'a']

## Tamaño y dimensión de un array
Un arreglo tiene dos propiedades básicas que nos dicen mucho acerca de su estructura: tamaño y dimensión.

Considemos el arreglo `arr2d`. Éste se creó a partir de una lista de listas. O sea, tiene dos dimensiones. Un arreglo de dos dimensiones se puede mostrar como renglones y columnas, i.e. una matriz.

Si hubiéramos creado el array a partir de una lista de lista de listas, entonces serían 3 dimensiones, i.e. un cubo.

Supogamos que recibimos un arreglo de numpy que no creamos nosotros. ¿Qué cosas queremos explorar para conocer bien este arreglo?

Bueno, unas buenas preguntas que querríamos contestar son:
- ¿Cuál es la dimensión del arreglo? ¿es de 1, 2 o más dimensiones? `ndim`
- ¿Cuántos elementos hay en cada dimensión? `shape`
- ¿Cuál es el tipo de dato? `dtype`
- ¿Cuál es el número total de elementos? `size`
- Algunos ejemplos/elementos del arreglo

Comencemos

In [29]:
# Crear arreglo de dos dimensiones con 3 filas y 4 columnas
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [30]:
# shape
print('Shape: ', arr2.shape)

# dtype
print('Datatype: ', arr2.dtype)

# size
print('Size: ', arr2.size)

# ndim
print('Num Dimensions: ', arr2.ndim)

Shape:  (3, 4)
Datatype:  float64
Size:  12
Num Dimensions:  2


---

## Acceder a los elementos del arreglo
Podemos extraer elementos o porciones específicos de un arreglo utilizando índices o `indexing` empezando por $0$. Esto es similar a cómo lo hacemos con listas en Python.

Pero a diferencia de las listas, los numpy arrays aceptan (opcionalmente) la misma cantidad de parámetros para indexar que el número de dimensiones que tiene el array.

Esto último es algo confuso, y no hay mejor manera que ilustrarlo que con un ejemplo:


In [31]:
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

Podemos extraer un elemento específico `(i, j)` en donde `i` es la fila y `j` la columna

In [32]:
arr2[1, 1]

np.float64(4.0)

También podemos extraer "rangos"

In [33]:
# Extraer las primeras 3 filas y las primeras 3 columnas
arr2[:3, :3]

array([[1., 2., 3.],
       [3., 4., 5.],
       [5., 6., 7.]])

Esto **no** se puede hacer en listas

In [34]:
list2[:2, :2]

TypeError: list indices must be integers or slices, not tuple

Adicionalmente, en los numpy arrays existe algo que se llama `boolean indexing` o indexación lógica. Un `boolean index` o índice lógico.

Un array de índices lógicos es de exactamente la misma forma (`shape`) que el array que estamos filtrando, sólo que contiene únicamente valores booleanos (`True` o `False`). Los valores que estén en los índices Verdaderos son los que va a arrojar nuestro filtro.

In [35]:
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [36]:
#Obtengamos el output booleano de aplicar una comparación a todo nuestro numpy array
b = arr2 > 4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

Como podemos ver, b ahora es una matriz de $3 \times 4$ con puros valores booleanos. El valor `True` está en todas las  posiciones en las que se cumplió que el elemento era $ > 4$

Con esta matriz de valores booleanos, podemos filtrar nuestra matriz original y obtener los valores que estén en posiciones verdaderas,

In [37]:
arr2[b]

array([5., 6., 5., 6., 7., 8.])

## Valores faltantes e infinitos
Es muy común recibir conjuntos de datos que tengan uno que otro valor en NA. Con numpy podemos representar valores faltantes con `np.nan` e infinitos con `np.inf`. Agreguemos algunos de estos valores a `arr2`

In [38]:
arr2[1,1] = np.nan  # no es un número
arr2[1,2] = np.inf  # infinito
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

Vamos a reemplazar todos los valores `nan` e `inf` con un $-1$

In [39]:
valores_faltantes_bool = np.isnan(arr2) | np.isinf(arr2)

In [40]:
valores_faltantes_bool

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [41]:
arr2[valores_faltantes_bool] = -1
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

---

## Calcular media, mínimo y máximo

Un ndarray viene ya con algunos métodos útiles. Unos de éstos nos permiten calcular medidas básicas

In [42]:
print("Hola mundo")

Hola mundo


In [43]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [44]:
print("Media: ", arr2.mean())
print("Valor máximo: ", arr2.max())
print("Valor mínimo: ", arr2.min())

Media:  3.5833333333333335
Valor máximo:  8.0
Valor mínimo:  -1.0


In [45]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

Sin embargo, estos valores exploraron toda la matriz. Podemos obtener los mismos valores pero para filas y columnas utilizando `np.amin`

In [46]:
print("Valores mínimos en columnas", np.amin(arr2, axis=0))

Valores mínimos en columnas [ 1. -1. -1.  4.]


In [47]:
print("Valores mínimos en filas: ", np.amin(arr2, axis=1))

Valores mínimos en filas:  [ 1. -1.  5.]


In [48]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

---

## Crear un arreglo a partir de otro arreglo
En Numpy la alocación de memoria sigue la misma lógica que en Python: si asignamos una porción de un array a una nueva variable, y modificamos elementos de esta nueva variable, entonces los cambios se verán reflejados también en nuestro array original. Para evitar este comportamiento (si eso es lo que queremos) utilizamos el método `copy()`.

In [49]:
arr2_nuevo = arr2[:2,:2]
arr2_nuevo[:1, :1] = 100  # el 100 se va a reflejar también en el array original arr2

In [50]:
# Veamos arr2 (original)
arr2

array([[100.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

Y ahora veamos `arr2_nuevo`

In [51]:
arr2_nuevo

array([[100.,   2.],
       [  3.,  -1.]])

In [52]:
#Para evitar esto vamos a usar copy
arr2_nuevo_2 = arr2[:2, :2].copy()
arr2_nuevo_2[0, 0] = 102  # 102 no saldrá en arr2
arr2

array([[100.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [53]:
arr2_nuevo_2

array([[102.,   2.],
       [  3.,  -1.]])

---

## Crear secuencias, repeticiones y números aleatorios

`np.arange`

In [54]:
# El límite inferior es 0 por defecto
print(np.arange(5))
nuevo_arr = np.arange(10)

[0 1 2 3 4]


In [55]:
type(nuevo_arr)

numpy.ndarray

In [61]:
# 0 a 9
print(np.arange(0, 9))

[0 1 2 3 4 5 6 7 8]


In [60]:
# 0 a 9 de 2 en 2
print(np.arange(0, 9, 2))

[0 2 4 6 8]


In [58]:
# 10 a 1, en decrementos de 1
print(np.arange(10, 0, -1))

[10  9  8  7  6  5  4  3  2  1]


Podemos poner límite inferior y superior con `np.arange`, pero si queremos enfocarnos en el número de elmentos que queremos generar, entonces tenemos que concentrarnos en el valor del incremento/decremento (`step`)

Digamos que queremos generar exactamente 10 valores entre 1 y 50.

Podemos usar `np.linspace`

In [62]:
# Empieza en 1, terminar en 50, creando 10 números enteros
np.linspace(start=1, stop=50, num=20, dtype=int)

array([ 1,  3,  6,  8, 11, 13, 16, 19, 21, 24, 26, 29, 31, 34, 37, 39, 42,
       44, 47, 50])

Un buen observador se dará cuenta que nuestros elementos no están espaciados uniformemente. Esto se debe a que especificamos que el tipo de dato era entero.

---

## Crear arreglos de $1's$ y $0's$

A menudo tendremos la necesidad de crear vectores o matrices que tengan únicamente valores de $1$ o $0$. Numpy hace esto muy fácil

In [63]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [64]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

---

## Crear secuencias repetidas

In [65]:
a = [1,2,3]

# Repetir todo el arreglo 'a' dos veces
print('Tile:   ', np.tile(a, 2))

# Repetir cada elemento de 'a' dos veces
print('Repeat: ', np.repeat(a, 4))


Tile:    [1 2 3 1 2 3]
Repeat:  [1 1 1 1 2 2 2 2 3 3 3 3]


In [66]:
import random
random.randint(0,100)

11

---

## Generar números aleatorios
Numpy tiene un módulo `random` con funciones últiles para generar números aleatorios de cualquier `shape`

In [69]:

print("Números aleatorios entre [0,1) de tamaño  2,2")
print(np.random.rand(0,1))

Números aleatorios entre [0,1) de tamaño  2,2
[]


In [70]:
print("Números aleatorios de una distribución normal con media=0 y varianza=1 de tamaño 2,2")
print(np.random.randn(2,2))

Números aleatorios de una distribución normal con media=0 y varianza=1 de tamaño 2,2
[[ 1.18932855 -1.08005896]
 [-1.08663523  1.17232451]]


In [71]:
print("Enteros aleatorios entre [0,10) de tamaño 2,2")
print(np.random.randint(0, 100, size=[5,5]))

Enteros aleatorios entre [0,10) de tamaño 2,2
[[93 81 59 28 14]
 [31 99  0 12  4]
 [26 94 70 65 39]
 [ 8 25  2 44 24]
 [48 57 33 97 89]]


In [72]:
print("Genera un número aleatorio entre [0,1)")
print(np.random.random())

Genera un número aleatorio entre [0,1)
0.5772916798615649


In [73]:
print("Elige 10 elementos de una lista (los resultados son equiprobables)")
print(np.random.choice(['Cara', 'Sol'], size=10))

Elige 10 elementos de una lista (los resultados son equiprobables)
['Cara' 'Cara' 'Cara' 'Sol' 'Cara' 'Sol' 'Cara' 'Cara' 'Sol' 'Sol']


In [80]:
print("Elige 10 elementos de una lista. Cada uno con una probablidad p")
print(np.random.choice(['Cara', 'Sol'], size=10, p=[.1, .9]))

Elige 10 elementos de una lista. Cada uno con una probablidad p
['Sol' 'Sol' 'Sol' 'Sol' 'Sol' 'Sol' 'Sol' 'Sol' 'Sol' 'Sol']


Cada que corramos el código anterior, obtendremos valores diferentes ya que estamos generando números aleatorios.

Existen casos en los que queremos números pseudoaleatorios para poder reproducir nuestros resultados. Para esto utlizamos una semilla

In [75]:
# ponemos una semilla 100 para reproducibilidad
np.random.seed(100)
print(np.random.rand(2,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


En todo script de python, si colocamos una semilla de 100 y ejecutamos `np.random.rand(2,2)` deberíamos obtener exactamente el mismo resultado. Esto es útil porque la reproducibilidad es indispensable en investigación. O sea, queremos que otras personas sean capaces de reproducir nuestros resultados.

---
## Obtener valores únicos y frecuencias absolutas

In [81]:
np.random.seed(1)
arr_rand = np.random.randint(0, 10, size=100)
arr_rand

array([5, 8, 9, 5, 0, 0, 1, 7, 6, 9, 2, 4, 5, 2, 4, 2, 4, 7, 7, 9, 1, 7,
       0, 6, 9, 9, 7, 6, 9, 1, 0, 1, 8, 8, 3, 9, 8, 7, 3, 6, 5, 1, 9, 3,
       4, 8, 1, 4, 0, 3, 9, 2, 0, 4, 9, 2, 7, 7, 9, 8, 6, 9, 3, 7, 7, 4,
       5, 9, 3, 6, 8, 0, 2, 7, 7, 9, 7, 3, 0, 8, 7, 7, 1, 1, 3, 0, 8, 6,
       4, 5, 6, 2, 5, 7, 8, 4, 4, 7, 7, 4])

In [82]:
vals_unicos, frecuencias = np.unique(arr_rand, return_counts=True)
print("Elementos únicos: ", vals_unicos)
print("Frecuencias      :", frecuencias)

Elementos únicos:  [0 1 2 3 4 5 6 7 8 9]
Frecuencias      : [ 9  8  7  8 11  7  8 18 10 14]


In [83]:
2**32

4294967296